# Generated by Django 5.2.4 on 2025-07-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='09:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Очікує підтвердження', max_length=32),
        ),
    ]
