# Generated by Django 5.2.4 on 2025-11-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_result_photos_booking_result_videos'),
        ('services', '0005_additionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_services',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='services.additionalservice'),
        ),
    ]
