# Generated by Django 5.2.4 on 2025-07-24 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_description'),
        ('services', '0004_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
    ]
