# Generated by Django 5.2.4 on 2025-11-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_portfolio_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ласкаво просимо до нашої фотостудії', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(default='Ми створюємо незабутні моменти та професійні фотографії для ваших особливих подій.', verbose_name='Опис')),
                ('contact_email', models.EmailField(default='info@studio.com', max_length=254, verbose_name='Email для контактів')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='Адреса')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Контент головної сторінки',
                'verbose_name_plural': 'Контент головної сторінки',
            },
        ),
    ]
