# Generated by Django 5.2.4 on 2025-11-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_homepagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_addresses',
            field=models.JSONField(blank=True, default=list, verbose_name='Адреси (список)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_emails',
            field=models.JSONField(blank=True, default=list, verbose_name='Email для контактів (список)'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='contact_phones',
            field=models.JSONField(blank=True, default=list, verbose_name='Телефони (список)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адреса (застаріле)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@studio.com', max_length=254, verbose_name='Email (застаріле)'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (застаріле)'),
        ),
    ]
