# Generated by Django 4.2.7 on 2025-11-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_homepagecontent_contact_addresses_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-id']},
        ),
    ]
