# Generated by Django 4.2.7 on 2025-12-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_portfolio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='guest_promo_text',
            field=models.CharField(blank=True, default='Зареєструйтесь, щоб отримати персональну знижку на фотосесію.', max_length=255, verbose_name='Текст для гостей (незареєстрованих користувачів)'),
        ),
    ]
