# Generated by Django 5.2.4 on 2025-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='work_days',
            field=models.CharField(default='0,1,2,3,4', help_text='Дні тижня через кому, коли працює (0=Пн, 6=Нд)', max_length=20),
        ),
        migrations.AddField(
            model_name='photographer',
            name='work_end',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AddField(
            model_name='photographer',
            name='work_start',
            field=models.TimeField(default='09:00'),
        ),
    ]
