# Generated by Django 4.2.7 on 2025-11-27 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0003_photographer_work_days_photographer_work_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographer',
            name='work_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='work_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
