# Generated by Django 5.2.4 on 2025-07-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Тривалість у хвилинах'),
        ),
    ]
