# Generated by Django 4.2.7 on 2025-12-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_additionalservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location_address',
            field=models.TextField(blank=True, help_text='Адреса студії або локація клієнта (наприклад, для фотосесії весілля). Залиште порожнім, якщо локація вибирається окремо.', null=True, verbose_name='Адреса локації'),
        ),
    ]
