# Generated by Django 5.2.4 on 2025-07-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Користувач'), ('photographer', 'Майстер'), ('admin', 'Адміністратор')], default='user', max_length=20),
        ),
    ]
