# Generated by Django 5.2.4 on 2025-11-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_discount',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
